version: '3.7'

# 컴퓨터들
services:

  # 컴퓨터이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./myEmail.js:/myfolder/myEmail.js
      - ./phone.js:/myfolder/phone.js
      - ./swagger/:/myfolder/swagger/
      - ./user.js/:/myfolder/user.js
      - ./controllers/:/myfolder/controllers/
    ports:
      - 3000:3000


  # 컴퓨터이름
  my-database:
    image: mongo:5
    ports:
      - 27017:27017